name: Build Kivy APK

on:
  workflow_dispatch: {}   # bot√≥n "Run workflow" en Actions

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install OS deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip autoconf automake libtool pkg-config \
            zlib1g-dev libncurses5 libstdc++6 openjdk-17-jdk \
            libffi-dev libssl-dev

      - name: Install Buildozer & Python deps
        run: |
          python -m pip install --upgrade pip
          pip install "cython<3.0" buildozer

      - name: Build debug APK
        run: buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: MemoryMatch-APK
          path: bin/*.apk
          if-no-files-found: error
